function [S, C, gi, vgi, origEvolved, bleachStateTemp, optProp] = iterateOneReef(iteratorHandle, timeSteps, S, C, dt, ...
                        temp, OA, omega, vgi, gi, MutVx, SelVx, C_seed, S_seed, suppressSI, ...
                        superSeedFraction, superMode, superAdvantage, oneShot, ...
                        bleachStateTemp, bleachParams, coralSymConstants)
% iterateOneReef Try proportionality constants until a bleaching target
% is met.
%
% To calibrate to the Donner database, each reef will be tested against actual
% or statistically estimated bleaching data.  The proportionality constant which
% best matches the data will be stored and used in later global runs.
%
[S, C, gi, vgi, origEvolved, bleachStateTemp] = iteratorHandle(timeSteps, S, C, dt, ...
           temp, OA, omega, vgi, gi, MutVx, SelVx, C_seed, S_seed, suppressSI, ...
           superSeedFraction, superMode, superAdvantage, oneShot, ...
           bleachStateTemp, bleachParams, coralSymConstants);
optProp = 1.1;
end

