% This generates Figure 2 in the submitted paper, but with an extra row showing
% results with evolution and shuffling.
names = { ...
    'GlobalCoralCover_rcp26_E0OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp45_E0OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp85_E0OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp26_E0OA0_SymStrategy9Adv1.00C', ...
    'GlobalCoralCover_rcp45_E0OA0_SymStrategy9Adv1.00C', ...
    'GlobalCoralCover_rcp85_E0OA0_SymStrategy9Adv1.00C', ...
    'GlobalCoralCover_rcp26_E1OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp45_E1OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp85_E1OA0_SymStrategy9Adv0.00C', ...
    'GlobalCoralCover_rcp26_E1OA0_SymStrategy9Adv1.00C', ...
    'GlobalCoralCover_rcp45_E1OA0_SymStrategy9Adv1.00C', ...
    'GlobalCoralCover_rcp85_E1OA0_SymStrategy9Adv1.00C'
    };
names = strcat('../FigureData/CoverPanels_Figure2/', names);
titles = { ...
    '(a) RCP 2.6', ...
    '(b) RCP 4.5', ...
    '(c) RCP 8.5', ...
    '(d)', ... 
    '(e)', ...
    '(f)', ...
    '(g)', ... 
    '(h)', ...
    '(i)', '(j)', '(k)', '(l)'};

for i = 1:length(names)
    n = names{i};
    hSingle(i) = open(strcat(n,'.fig'));
    pax(i) = gca;
end

figure('color', 'w');
set(gcf,...
    'OuterPosition',[11 1 1440 1440]);

% Subplot arguments are rows, columns, counter by rows first
% Row labels now describe the adaptation:
rowLabel{1} = {'No adaptation','% Cover'};
rowLabel{2} = {'Symbiont', 'shuffling','% Cover'};
rowLabel{3} = {'Evolution','% Cover'};
rowLabel{4} = {'Evolution and', 'Shuffling','% Cover'};
for i = 1:length(names)
    P = subplot(length(names)/3, 3, i); % rows, then columns
    copyobj(get(pax(i),'children'),P);
    %n = strrep(names{i}, '_', ' ');
    title(titles{i});
    xlim([1950 2100]);
    if mod(i, 3) == 1 
        % ylabel('% Cover');
        ylabel(rowLabel{(i-1)/3 + 1});
        set(gca, 'XTick', [1950 2000 2050 2100]);
    else
        set(gca, 'XTick', [2000 2050 2100]);
    end
    set(P,'FontSize',28);
    % Make subplots a little wider. (kept as an example)
    %pos = get(gca, 'Position');
    %pos(1) = pos(1) - 0.005;
    %pos(3) = pos(3) + 0.01;
    %set(gca, 'Position', pos);
end
% Clean up single plots
% For some reason, closing inside the loop above causes trouble.
for i = 1:length(names)
    close(hSingle(i));
end
%leg = legend('show');
%set(leg,...
%    'Position',[0.858 0.489 0.140 0.162],...
%    'FontSize',18);
