%function spinupFigure(YData1, XData1, YData2, X1, YMatrix1, YData3, YData4)
%CREATEFIGURE(YData1, XData1, YData2, X1, YMatrix1, YData3, YData4)
% To use this script, load SpinupData from ../FigureData and then run this
% script.
load('../FigureData/SpinupData.mat');
% Convert to the names in the auto-generated data
XData1 = xPatch;
X1 = xYears;
YData1 = mass20Patch;
YData2 = branch80Patch;
YMatrix1 = [mass20; branch80; branchInverse; massInverse]; % Y for all 4 curves
YData3 = massInversePatch;
YData4 = branchInversePatch;


%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  YDATA2:  patch ydata
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YDATA3:  patch ydata
%  YDATA4:  patch ydata

%  Auto-generated by MATLAB on 25-Jul-2020 08:36:40

% Create figure
figure('Name','Global Coral Cover','OuterPosition',[1 1 1177 715]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create patch
patch('DisplayName','25th - 75th percentile','YData',YData1,'XData',XData1,...
    'FaceAlpha',0.2,...
    'LineStyle','none',...
    'FaceColor',[1 0.5 0.5]);

% Create patch
patch('DisplayName','25-75','YData',YData2,'XData',XData1,'FaceAlpha',0.2,...
    'LineStyle','none',...
    'FaceColor',[0 0.447058826684952 0.74117648601532]);


% Create patch
patch('DisplayName','25th - 75th percentile','Parent',axes1,'YData',YData3,...
    'XData',XData1,...
    'FaceAlpha',0.2,...
    'LineStyle','none',...
    'FaceColor',[0.466666668653488 0.674509823322296 0.18823529779911]);

% Create patch
patch('DisplayName','25th - 75th percentile','Parent',axes1,'YData',YData4,...
    'XData',XData1,...
    'FaceAlpha',0.2,...
    'LineStyle','none',...
    'FaceColor',[0.749019622802734 0 0.749019622802734]);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Mounding, 20% start','Color',[1 0 0]);
set(plot1(4),'DisplayName','Mounding, inverse start',...
    'Color',[0.466666668653488 0.674509823322296 0.18823529779911]);
set(plot1(2),'DisplayName','Branching, 80% Start',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(3),'DisplayName','Branching, inverse start',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);


% Create ylabel
ylabel('Percent of Carrying Capacity, K');

% Create xlabel
xlabel({'Year'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XTick',[1900 2000 2100 2200],'YTick',...
    [0 20 40 60 80 100]);
% Create legend
%legend1 = legend(axes1,'show');
% Just the lines!
legend1 = legend(plot1);
set(legend1,...
    'Position',[0.423251203865581 0.347552450761928 0.19796091297874 0.225174818755864],...
    'FontSize',13);

